apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: {{ .Values.event.eventSourceName }}
  namespace: {{ .Values.event.namespace }}
spec:
  service:
    ports:
    - port: {{ .Values.event.port }}
      targetPort: {{ .Values.event.port }}
  github:
    {{ .Values.event.eventName | nindent 3 }}:
      owner: tiwarisanjay
      repository: tf-create-k8-namepsace
      webhook:
        endpoint: {{ .Values.event.eventName | printf "/%s" }} #End or your webhook url It can be anything 
        port: {{ .Values.event.port | quote }}
        method: POST
        url: http://35.193.14.221:12000
      events:
        - "*"
      apiToken:
        name: github-access
        key: token
      insecure: true
      active: true
      contentType: json