apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: hello-world-sensor
  namespace: {{ .Values.event.namespace }}
spec:
  template:
    serviceAccountName: {{ .Values.event.serviceAccount }}
  dependencies:
  - name: payload
    eventSourceName: gke-test-es
    eventName: gke-test
  triggers:
  - template:
      name: payload
      k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          parameters:
            - src:
                dependencyName: payload
                dataKey: body.message
              dest: spec.templates.0.dag.tasks.0.arguments.parameters.0.value
          source:
            resource: #============== Terrafrom Workflow template
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: hello-world-
                namespace: argo-events
                labels:
                  workflows.argoproj.io/archive-strategy: "false"
              spec:
                entrypoint: full
                serviceAccountName: {{ .Values.workflow.serviceAccount }}
                templates:
                - name: full
                  dag:
                    tasks:
                    - name: echo-task-1
                      template: echo-task
                      arguments:
                        parameters:
                        - name: message
                          value: Hello World
                    - name: echo-task-2
                      template: echo-task
                      arguments:
                        parameters:
                        - name: message
                          value: Hello World
                - name: echo-task
                  inputs:
                    parameters:
                    - name: message
                  container:
                    image: alpine
                    command: [echo]
                    args:
                    - {{`"{{inputs.parameters.message}}"`}}
