apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.event.serviceAccount }}
  namespace: {{ .Values.event.namespace }}
---
# Similarly you can use a ClusterRole and ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: operate-wf-role
  namespace: {{ .Values.event.namespace }}
rules:
  - apiGroups:
      - argoproj.io
    verbs:
      - "*"
    resources:
      - workflows
      - workflowtemplates
      - cronworkflows
      - clusterworkflowtemplates
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operate-wf-role-binding
  namespace: {{ .Values.event.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: operate-wf-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.event.serviceAccount }}
    namespace: {{ .Values.event.namespace }}
    
